description: for debug
runner: r001
device: cuda
batch_size: 48
max_epoch: 1
fobj: ce
model:
    model_type: resnet18
    pretrained: true
optimizer: 
    optim_type: adam
    lr: 0.0003
scheduler:
    scheduler_type: pass
sampler:
    sampler_type: random
split: 
    split_type: cskf
    split_num: 5
